### ISSUE TITLE
Signal munki recipe is throwing out an error which I believe is due to change in contents of PRODUCT_UPDATE_URL

### ISSUE THREAD

**Issue by fseesink** [autopkg/jaharmi-recipes#57]
Noticed AutoPkg wasn't pulling down the latest Signal version (v5.27.0).  Went to check, and got the following error:
```
Error Running Recipes

Use of undefined key in variable substitution: 'version'
No match found on URL: https://updates.signal.org/desktop/latest-mac.yml
Failed.
```

I believe the issue lies in what I think is a change in `https://updates.signal.org/desktop/latest-mac.yml` used in the `Signal.download.recipe`.  As I type this, that file reads as follows:

```
version: 5.27.0
files:
  - url: signal-desktop-mac-x64-5.27.0.zip
    sha512: p+QRmtueKsFPLCpkaV9J/mPXROYB8y2BNttYYdywwLVACnQXgny0hECDoPPmUVFeX7lYzvc0L9+/73oqn9z0yg==
    size: 151224127
  - url: signal-desktop-mac-arm64-5.27.0.zip
    sha512: 32SQXVMYHhvBDCUSk2aMTyMYzjrjePbrdQA1TKWJ8sDbCL7HuqqBgzov8v19soiCYNQAiGHK8e90oHKaCTZjXQ==
    size: 150183751
  - url: signal-desktop-mac-x64-5.27.0.dmg
    sha512: hdUH/rREnPa8mR3/l42KutZ3HqhLfAJn70iIq780GMdiYv+qzq0XlieKH0pTuXdwxUPahtGfnobRPH2nolI8OA==
    size: 155961350
  - url: signal-desktop-mac-arm64-5.27.0.dmg
    sha512: eXJN1XoeeLiDwycD4uMZspBci+Dtl79qU9abTwAj/bykcRXf33qrhjbwS59SBmuMWyyXJrJ5DF74Vv/bFtlRVw==
    size: 155197098
  - url: signal-desktop-mac-universal-5.27.0.dmg
    sha512: +iYFMF6CBn9wgqh2/ezMzWSMoJQGYVRecnmXBGk5as2wuZy0YqOQ6fDnydHLtCqXz40JSWNNo4QAVcImhQ5Qow==
    size: 245329975
path: signal-desktop-mac-x64-5.27.0.zip
sha512: p+QRmtueKsFPLCpkaV9J/mPXROYB8y2BNttYYdywwLVACnQXgny0hECDoPPmUVFeX7lYzvc0L9+/73oqn9z0yg==
releaseDate: '2022-01-04T20:19:58.850Z'
```

It appears they have added links to binary-specific versions (`x64` vs. `arm64`) as well as changing the name of the Universal Binary file (different from what Signal.download.recipe is trying to pattern match on) to `signal-desktop-mac-universal-5.27.0.dmg`.  So I believe the download recipe is not finding a version at all as it is looking for a pattern that does not exist in the file now.

The easiest solution is likely searching for the Universal Binary pattern only and being sure to get the right.
